### ISSUE TITLE
DeepConsensusPicking fails

### ISSUE THREAD

**Issue by DStrelak** [I2PC/scipion-em-xmipp#423]
For more details, please contact  @shuaishuairuirui 
SW: 
Cuda 11
latest release of xmipp

Maybe it's somehow related to https://github.com/I2PC/xmipp/issues/395 ?
`E tensorflow/stream_executor/cuda/cuda_blas.cc:428] failed to run cuBLAS routine: CUBLAS_STATUS_EXECUTION_FAILED`
I also see some error regarding the Out Of Memory, but I"m not sure if it's cause or consequence.

Log:
```
00677: 2021-07-13 18:54:17.780813: I tensorflow/compiler/xla/service/service.cc:176] StreamExecutor device (0): NVIDIA GeForce RTX 3090, Compute Capability 8.6
00678: WARNING:tensorflow:From /home/amax/anaconda3/envs/xmipp_DLTK_v0.3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.
00679:
00680: WARNING:tensorflow:From /home/amax/anaconda3/envs/xmipp_DLTK_v0.3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.
00681:
00682: WARNING:tensorflow:From /home/amax/anaconda3/envs/xmipp_DLTK_v0.3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.
00683:
00684: WARNING:tensorflow:From /home/amax/anaconda3/envs/xmipp_DLTK_v0.3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:174: The name tf.get_default_session is deprecated. Please use tf.compat.v1.get_default_session instead.
00685:
00686: WARNING:tensorflow:From /home/amax/anaconda3/envs/xmipp_DLTK_v0.3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:190: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.
00687:
00688: WARNING:tensorflow:From /home/amax/anaconda3/envs/xmipp_DLTK_v0.3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:199: The name tf.is_variable_initialized is deprecated. Please use tf.compat.v1.is_variable_initialized instead.
00689:
00690: WARNING:tensorflow:From /home/amax/anaconda3/envs/xmipp_DLTK_v0.3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:206: The name tf.variables_initializer is deprecated. Please use tf.compat.v1.variables_initializer instead.
00691:
00692: WARNING:tensorflow:From /home/amax/anaconda3/envs/xmipp_DLTK_v0.3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:1834: The name tf.nn.fused_batch_norm is deprecated. Please use tf.compat.v1.nn.fused_batch_norm instead.
00693:
00694: WARNING:tensorflow:From /home/amax/anaconda3/envs/xmipp_DLTK_v0.3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:133: The name tf.placeholder_with_default is deprecated. Please use tf.compat.v1.placeholder_with_default instead.
00695:
00696: WARNING:tensorflow:From /home/amax/anaconda3/envs/xmipp_DLTK_v0.3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:3976: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.
00697:
00698: WARNING:tensorflow:From /home/amax/anaconda3/envs/xmipp_DLTK_v0.3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:3980: The name tf.nn.avg_pool is deprecated. Please use tf.nn.avg_pool2d instead.
00699:
00700: WARNING:tensorflow:From /home/amax/anaconda3/envs/xmipp_DLTK_v0.3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
00701: Instructions for updating:
00702: Please use rate instead of keep_prob. Rate should be set to rate = 1 - keep_prob.
00703: WARNING:tensorflow:From /home/amax/anaconda3/envs/xmipp_DLTK_v0.3/lib/python3.7/site-packages/keras/optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.
00704:
00705: WARNING:tensorflow:From /home/amax/anaconda3/envs/xmipp_DLTK_v0.3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:3295: The name tf.log is deprecated. Please use tf.math.log instead.
00706:
00707: Training model 1/3
00708: current checkpoint name Runs/015987_XmippProtScreenDeepConsensus/extra/nnetData1/tfchkpoints_0/deepModel.hdf5
00709: Creating net.
00710: Model depth: 4
00711: nEpochs : 50.0 --> Epochs: 93.
00712: Training begins: Epoch 0/93
00713: WARNING:tensorflow:From /home/amax/anaconda3/envs/xmipp_DLTK_v0.3/lib/python3.7/site-packages/tensorflow_core/python/ops/math_grad.py:1424: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
00714: Instructions for updating:
00715: Use tf.where in 2.0, which has the same broadcast rule as np.where
00716: WARNING:tensorflow:From /home/amax/anaconda3/envs/xmipp_DLTK_v0.3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:986: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.
00717:
00718: WARNING:tensorflow:From /home/amax/anaconda3/envs/xmipp_DLTK_v0.3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:973: The name tf.assign is deprecated. Please use tf.compat.v1.assign instead.
00719:
00720: Epoch 1/93
00721: 2021-07-13 18:59:11.700261: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
00722: 2021-07-13 19:00:30.012900: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
00723: 2021-07-13 19:15:29.079521: E tensorflow/stream_executor/cuda/cuda_blas.cc:428] failed to run cuBLAS routine: CUBLAS_STATUS_EXECUTION_FAILED
00724: Traceback (most recent call last):
00725: File "/home/amax/software/scipion/software/em/xmipp/bin/xmipp_deep_consensus", line 210, in trainWorker
00726: l2RegStrength, auto_stop)
00727: File "/home/amax/software/scipion/software/em/xmipp/pylib/xmippPyModules/deepConsensusWorkers/deepConsensus_deepLearning1.py", line 190, in trainNet
00728: use_multiprocessing=True, verbose=2)
00729: File "/home/amax/anaconda3/envs/xmipp_DLTK_v0.3/lib/python3.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
00730: return func(*args, **kwargs)
00731: File "/home/amax/anaconda3/envs/xmipp_DLTK_v0.3/lib/python3.7/site-packages/keras/engine/training.py", line 1418, in fit_generator
00732: initial_epoch=initial_epoch)
00733: File "/home/amax/anaconda3/envs/xmipp_DLTK_v0.3/lib/python3.7/site-packages/keras/engine/training_generator.py", line 217, in fit_generator
00734: class_weight=class_weight)
00735: File "/home/amax/anaconda3/envs/xmipp_DLTK_v0.3/lib/python3.7/site-packages/keras/engine/training.py", line 1217, in train_on_batch
00736: outputs = self.train_function(ins)
00737: File "/home/amax/anaconda3/envs/xmipp_DLTK_v0.3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 2715, in call
00738: return self._call(inputs)
00739: File "/home/amax/anaconda3/envs/xmipp_DLTK_v0.3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
00740: fetched = self._callable_fn(*array_vals)
00741: File "/home/amax/anaconda3/envs/xmipp_DLTK_v0.3/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1472, in call
00742: run_metadata_ptr)
00743: tensorflow.python.framework.errors_impl.InternalError: 2 root error(s) found.
00744: (0) Internal: Blas GEMM launch failed : a.shape=(64, 512), b.shape=(512, 2), m=64, n=2, k=512
00745: [[{{node dense_2/MatMul}}]]
00746: [[metrics/acc/Mean/_333]]
00747: (1) Internal: Blas GEMM launch failed : a.shape=(64, 512), b.shape=(512, 2), m=64, n=2, k=512
00748: [[{{node dense_2/MatMul}}]]
00749: 0 successful operations.
00750: 0 derived errors ignored.
00751:
00752: During handling of the above exception, another exception occurred:
00753:
00754: Traceback (most recent call last):
00755: File "/home/amax/software/scipion/software/bindings/xmipp_base.py", line 107, in tryRun
00756: self.run()
00757: File "/home/amax/software/scipion/software/em/xmipp/bin/xmipp_deep_consensus", line 149, in run
00758: ScriptDeepScreeningTrain.trainWorker(**trainArgs)
00759: File "/home/amax/software/scipion/software/em/xmipp/bin/xmipp_deep_consensus", line 213, in trainWorker
00760: raise Exception("Out of gpu Memory. gpu # %d"%(gpuToUse))
00761: Exception: Out of gpu Memory. gpu # 0
00762: Traceback (most recent call last):
00763: File "/home/amax/anaconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/executor.py", line 148, in run
00764: self.step._run() # not self.step.run() , to avoid race conditions
00765: File "/home/amax/anaconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 248, in _run
00766: resultFiles = self._runFunc()
00767: File "/home/amax/anaconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 244, in _runFunc
00768: return self._func(*self._args)
00769: File "/home/amax/anaconda3/envs/scipion3/lib/python3.8/site-packages/xmipp3/protocols/protocol_screen_deepConsensus.py", line 992, in trainCNN
00770: self.runJob('xmipp_deep_consensus', args, numberOfMpi=1, env=self.getCondaEnv())
00771: File "/home/amax/anaconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 1389, in runJob
00772: self._stepsExecutor.runJob(self._log, program, arguments, **kwargs)
00773: File "/home/amax/anaconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/executor.py", line 65, in runJob
00774: process.runJob(log, programName, params,
00775: File "/home/amax/anaconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/utils/process.py", line 52, in runJob
00776: return runCommand(command, env, cwd)
00777: File "/home/amax/anaconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/utils/process.py", line 67, in runCommand
00778: check_call(command, shell=True, stdout=sys.stdout, stderr=sys.stderr,
00779: File "/home/amax/anaconda3/envs/scipion3/lib/python3.8/subprocess.py", line 364, in check_call
00780: raise CalledProcessError(retcode, cmd)
00781: subprocess.CalledProcessError: Command ' xmipp_deep_consensus -n Runs/015987_XmippProtScreenDeepConsensus/extra/nnetData1 --mode train -p Runs/015987_XmippProtScreenDeepConsensus/extra/particles_AND1.xmd -f Runs/015987_XmippProtScreenDeepConsensus/extra/particles_NOISE1.xmd:Runs/015987_XmippProtScreenDeepConsensus/tmp/addNegTrainParticles.xmd --trueW 1 --falseW 1:1 --effective_data_size 20000 -e 50.0 -l 0.0001 -r 1e-05 -m 3 -g 0' returned non-zero exit status 1.
00782: Protocol failed: Command ' xmipp_deep_consensus -n Runs/015987_XmippProtScreenDeepConsensus/extra/nnetData1 --mode train -p Runs/015987_XmippProtScreenDeepConsensus/extra/particles_AND1.xmd -f Runs/015987_XmippProtScreenDeepConsensus/extra/particles_NOISE1.xmd:Runs/015987_XmippProtScreenDeepConsensus/tmp/addNegTrainParticles.xmd --trueW 1 --falseW 1:1 --effective_data_size 20000 -e 50.0 -l 0.0001 -r 1e-05 -m 3 -g 0' returned non-zero exit status 1.
00783: FAILED: trainCNN, step 16, time 2021-07-13 19:15:30.202352
00784: ------------------- PROTOCOL FAILED (DONE 14/17)
```

**Comment by DaniDelHoyo** [comment]
I have looked or information about this issue and seems like it happens because of GPU memory problems, specially when there are several programs using it: https://stackoverflow.com/questions/43990046/tensorflow-blas-gemm-launch-failed , https://github.com/tensorflow/tensorflow/issues/11812 .

The optimal thing I guess would be not running several tensorflow programs in paralel, as they try to consume all the GPU, but seems like tunning some details of the TF configuration (tf.compat.v1.ConfigProto()) also may work.
However, as I cannot reproduce the error it would be difficult for me to check if it fixes the error. Any idea @DStrelak ?

**Comment by albertmena** [comment]
@DStrelak  or @DaniDelHoyo could you chek if still failing? https://github.com/I2PC/scipion-em-xmipp/pull/486/ could have fixed it.

**Comment by DaniDelHoyo** [comment]
I never managed to reproduce the error so I don't think I can say that it fixed it or not. Also, I haven't worked in this protocol for a while, so it may have changed substantially. Please ask @danielmarchan3
